project/dashboard/views.py
import json
import requests
import adal
import re
import os
from project.models import User ,Profession
from flask import Blueprint,render_template, redirect,url_for,request,flash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

dashboard_blueprint =   Blueprint(
    'dashboard',
    __name__,
    template_folder='templates'
)

@dashboard_blueprint.route("/")
def Index():
    resource_url = 'https://analysis.windows.net/powerbi/api'
    username='*****'
    password='****'

    client_id='4e4bf593-32b5-4d99-a860-bb26cdb0e2f7'
    AuthContext= adal.AuthenticationContext("https://login.windows.net/common")
    token=AuthContext.acquire_token_with_username_password(resource_url,username,password,client_id)
    #create_row_data = {'id': '1235','name':'Joel','created_on':'27/01/2018','modified_on':'27/01/2018','desc':'This is Joel!!'}
    #create_row_data={'grant_type': 'password','resource': 'https://analysis.windows.net/powerbi/api','client_id': '4e4bf593-32b5-4d99-a860-bb26cdb0e2f7','username': 'Bill.Reinstein@HCPdigitalinsights.com','password': 'Bilso1520'}
    #print(AuthContext)
    #print(token["accessToken"])
    accessToken=token["accessToken"]
    #print("======================================================")
    #print(accessToken)
    #print("======================================================")
    url="https://api.powerbi.com/v1.0/myorg/groups/42b9d168-fefb-4b3c-aa2d-af24fb08f4d8/reports"
    headers = {'Authorization': 'Bearer ' + accessToken,'Content-type': 'application/json', 'Accept': 'application/json'}
    response=requests.get(url, headers=headers)
    #print("-----------------------------------------")
    reportId=response.json()["value"][0]['id']
    #print(reportId)
    #print("-----------------------------------------")
    reportUrl=response.json()["value"][0]["webUrl"]+"/GenerateToken"
    #reportUrl="https://api.powerbi.com/v1.0/myorg/reports/"+response.json()["value"][0]['id']+"/GenerateToken"
    reportUrl="https://api.powerbi.com/v1.0/myorg/groups/42b9d168-fefb-4b3c-aa2d-af24fb08f4d8/reports/f01e98f3-abb9-4f51-bca3-a9eb419ee97e/GenerateToken"
    #print("reportUrl="+reportUrl)

    #headers = {'Authorization': 'Bearer ' + accessToken,'Content-type': 'application/json', 'Accept': 'application/json'}
    data1= {'allowSaveAs': 'false'}
    responseEmbedToken=requests.post(reportUrl,data=json.dumps(data1),headers=headers)
    #print("+++++++++++++++++++++++++++++++++++++++++")
    #print(responseEmbedToken.text)
    #print response.
    #print(responseEmbedToken.url)
    #print(responseEmbedToken.json()["token"])
    #print("++++++++++++++++++++++++++++++++++++++++++")
    embedurl="https://app.powerbi.com/reportEmbed?reportId="+reportId+"&groupId=42b9d168-fefb-4b3c-aa2d-af24fb08f4d8"
    configObj={'token':responseEmbedToken.json()["token"],'embedurl':embedurl,'reportid':reportId}
    #print(responseEmbedToken.json())
    #print(response.json()["value"][0].webUrl)
    #r = requests.post(url=api_url, json=create_row_data)
    #print(r.status_code, r.reason, r.text)
    profession=Profession.query.all()
    return render_template('dashboard/index.html',configObj=json.dumps(configObj))

@dashboard_blueprint.route("/campaign/<id>")
def Campaign(id):
    campaignId=id
    resource_url = 'https://analysis.windows.net/powerbi/api'
    #username='***'
    #password='***'
    PbiUserID       = os.environ['PbiUserID']
    PbiPassword     = os.environ['PbiPassword']
    print(current_user)
    profession=Profession.query.all()
    client_id='4e4bf593-32b5-4d99-a860-bb26cdb0e2f7'
    AuthContext= adal.AuthenticationContext("https://login.windows.net/common")
    token=AuthContext.acquire_token_with_username_password(resource_url,PbiUserID,PbiPassword,client_id)
    accessToken=token["accessToken"]
    url="https://api.powerbi.com/v1.0/myorg/groups/42b9d168-fefb-4b3c-aa2d-af24fb08f4d8/reports"
    headers = {'Authorization': 'Bearer ' + accessToken,'Content-type': 'application/json', 'Accept': 'application/json'}
    response=requests.get(url, headers=headers)
    reportId=response.json()["value"][0]['id']
    reportUrl=response.json()["value"][0]["webUrl"]+"/GenerateToken"
    #reportUrl="https://api.powerbi.com/v1.0/myorg/reports/"+response.json()["value"][0]['id']+"/GenerateToken"
    reportId="f01e98f3-abb9-4f51-bca3-a9eb419ee97e"
    reportId="187ffc03-1c8e-4cb8-a19c-d182c2b01b16"
    reportUrl="https://api.powerbi.com/v1.0/myorg/groups/42b9d168-fefb-4b3c-aa2d-af24fb08f4d8/reports/"+reportId+"/GenerateToken"
    data1= {
            'allowSaveAs'   : 'false',
            "accessLevel"   : "view",
            "identities"    : [
                                {
                                    "username":campaignId,
                                    "roles":["Campaign"],
                                    "datasets":["80529fbe-4cae-49aa-a27c-2106c3d8aad7"]
                                }
                              ]
            }

    responseEmbedToken=requests.post(reportUrl,data=json.dumps(data1),headers=headers)
    embedurl="https://app.powerbi.com/reportEmbed?reportId="+reportId+"&groupId=42b9d168-fefb-4b3c-aa2d-af24fb08f4d8"
    configObj={'token':responseEmbedToken.json()["token"],'embedurl':embedurl,'reportid':reportId}
    return render_template('dashboard/Pbi.html',profession=profession,configObj=json.dumps(configObj))


@dashboard_blueprint.route("/ProfessionalInsights")
def ProfessionalInsights():
    return render_template('dashboard/index.html')

@dashboard_blueprint.route("/ContentInsights")
def ContentInsights():
    return render_template('dashboard/ContentInsights.html')

@dashboard_blueprint.route("/DeviceTypes")
def DeviceTypes():
    return render_template('dashboard/DeviceType.html')

project/templates/base-login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HCP Digital Insights</title>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-NJXGk7R+8gWGBdutmr+/d6XDokLwQhF1U3VA7FhvBDlOq7cNdI69z7NQdnXxcF7k" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/mdg.css') }}">

<script src="{{ url_for('static', filename='js/tether.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/d3.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/crossfilter.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/dc.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/reductio.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/powerbi.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/mdg.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>

<body id="login">
{%block content%}
{%endblock%}
{% block footer %}
{%endblock%}
</body>
</html>

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HCP Digital Insights</title>
<!--
    
    --<link rel="stylesheet" href="{{ url_for('static', filename='css/hcpdigital.css') }}">--
    
    <script src="{{ url_for('static', filename='js/jquery-3.1.1.slim.min.js')}}"></script>

    -- IE10 viewport hack for Surface/desktop Windows 8 bug --
    <script src="{{ url_for('static', filename='js/ie10-viewport-bug-workaround.js')}}"></script>
  -->
<!--  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">-->
<link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome.min.css') }}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-NJXGk7R+8gWGBdutmr+/d6XDokLwQhF1U3VA7FhvBDlOq7cNdI69z7NQdnXxcF7k" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/mdg.css') }}"> 	
<script src="{{ url_for('static', filename='js/tether.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/powerbi.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/mdg.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/chosen.css') }}"> 	
<script type="text/javascript" src="{{ url_for('static', filename='js/chosen.jquery.js') }}"></script>
</head>
<body>
<header class="header">
    <nav class="navbar navbar-toggleable-md navbar-light fixed-top">
        <a class="nav-link dropdown-toggle navbar-toggleable-md navbar-toggler" href="#" data-toggle="dropdown" data-target="#mobile-nav" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle"></i> </a>
        <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='images/logo-insights.png')}}" height="70px" alt="HCP Digital Insights Logo" /></a>
        <div class="float-left"> <a href="#" class="button-left"><i class="far fa-bars"></i></a> </div>
        <div class="float-left client-name">{{customer_name}}</div>
        <div class="collapse navbar-collapse flex-row-reverse" id="mobile-nav">
            <ul class="navbar-nav">
                <li class="nav-item dropdown  user-menu"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{ url_for('static', filename='images/logo-mdg.png')}}" height="70px" alt="HCP Digital Insights Logo" /> <span class="hidden-xs"><i class="fas fa-user-circle"></i> {{current_user.username}}</span> </a>
                    <div class="dropdown-menu collapse"> <a class="dropdown-item" href="#">My Account</a> <a class="dropdown-item" href="#">Sample Link 2</a> <a class="dropdown-item" href="#">Sample Link 3</a> </div>
                </li>
            </ul>
        </div>
    </nav>
</header>
    
<div class="main fliph">
        <div class="sidebar left" id="sidenav">
            <ul class="list-sidebar bg-defoult">
                <li><a href="#"><i class="fas fa-ad"></i> <span class="nav-label">Campaign</span></a></li>
                <li><a href="#"><i class="fas fa-info-circle"></i> <span class="nav-label">Campaign Information</span></a></li>
                <li> <a href="#" data-toggle="collapse" data-target="#insights-dashboards" class="collapsed" > <i class="fas fa-tachometer-alt"></i> <span class="nav-label"> Insights Dashboards</span> </a>
                    <ul class="sub-menu collapse" id="insights-dashboards">
                        <li><a href="{{url_for('dashboard.DeviceTypes')}}">Device Types</a></li>
                        <li><a href="{{url_for('dashboard.ProfessionalInsights')}}">Professional Insights</a></li>
                        <li><a href="{{url_for('dashboard.ContentInsights')}}">Content Insights</a></li>
                    </ul>
                </li>
                <!--
                    <li> <a href="#" data-toggle="collapse" data-target="#dashboard-filters" class="collapsed" > <i class="fas fa-filter"></i> <span class="nav-label">Dashboard Filters</span> </a>
                    <ul class="sub-menu collapse" id="dashboard-filters">
                        <li> <span class="spaced"><label for="county">Filter 1:</label>
                            <div class="selectwrap">
                            <select id="county">
                                <option value="ADA COUNTY">ADA COUNTY</option>
                                <option value="ADAIR COUNTY">ADAIR COUNTY</option>
                                <option value="ADAMS COUNTY">ADAMS COUNTY</option>
                                <option value="ADDISON COUNTY">ADDISON COUNTY</option>
                            </select></div></span>
                        </li>
                        <li> <span class="spaced"><label for="ddfilter2">Filter 2:</label>
                            <div class="selectwrap">
                            <select id="ddfilter2">
                                <option value="ADA COUNTY">Filter Value1</option>
                                <option value="ADAIR COUNTY">Filter Value2</option>
                                <option value="ADAMS COUNTY">Filter Value3</option>
                                <option value="ADDISON COUNTY">Filter Value4</option>
                            </select></div></span>
                        </li>
                        <li> <span class="spaced"><label for="ddfilter3">Filter 3:</label>
                            <div class="selectwrap">
                            <select id="ddfilter3">
                                <option value="ADA COUNTY">Filter Value1</option>
                                <option value="ADAIR COUNTY">Filter Value2</option>
                                <option value="ADAMS COUNTY">Filter Value3</option>
                                <option value="ADDISON COUNTY">Filter Value4</option>
                            </select></div></span>
                        </li>
                    </ul>
                </li>
                -->
                <li><a href="#"><i class="fas fa-magic"></i> <span class="nav-label">Campaign Optimization</span></a></li>
                <li><a href="#"><i class="fas fa-file-export"></i> <span class="nav-label">Export Dashboard</span></a></li>
                <li><a href="#"><i class="fas fa-print"></i> <span class="nav-label">Print Dashboard</span></a></li>
                <li><a href="#"><i class="fas fa-question-circle"></i> <span class="nav-label">Support</span></a></li>
            </ul>
        </div>
    
    <div class="main-content">
        <div class="container-fluid">
    <!-- Page Content -->
      {%block content%}
      {%endblock%}
      {% block footer %}
<!--
        <footer class="footer">
          <div class="container">
            <span class="text-muted">Place sticky footer content here.</span>
          </div>
        </footer>
      -->  
        {%endblock%} 
        </div>
     </div>
</div>   
    

  
  </body>
</html>

project/templates/base1.html
<html>
<head>
  <meta charset="utf-8">
  <title>Dashboard Starter UI, by Keen IO</title>
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />

  <!-- Demo Dependencies -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

  <!-- keen-analysis@1.2.2 -->
  <script src="https://d26b395fwzu5fz.cloudfront.net/keen-analysis-1.2.2.js" type="text/javascript"></script>

  <!-- keen-dataviz@1.1.3 -->
  <link href="https://d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.3.css" rel="stylesheet" />
  <script src="https://d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.3.js" type="text/javascript"></script>

  <!-- Dashboard -->

  <link rel="stylesheet" href="{{ url_for('static', filename='css/keen-dashboards.css') }}">
  <script type="text/javascript" src="{{ url_for('static', filename='js/starter-kit.js')}}"></script>
</head>
<body class="keen-dashboard" style="padding-top: 80px;">

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="../">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="navbar-brand" href="./">Dashboard Starter UI</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
          <li><a href="https://keen.io">Home</a></li>
          <li><a href="https://keen.io/team">Team</a></li>
          <li><a href="https://github.com/keenlabs/dashboards/tree/gh-pages/examples/starter-kit">Source</a></li>
          <li><a href="https://groups.google.com/forum/#!forum/keen-io-devs">Community</a></li><li><a href="http://stackoverflow.com/questions/tagged/keen-io?sort=newest&pageSize=15">Technical Support</a></li>
        </ul>
      </div>
    </div>
  </div>
  
      {%block content%}
      {%endblock%}
<!-- /.container -->
  <script type="text/javascript" src="{{ url_for('static', filename='js/keen-analytics.js')}}"></script>
  <script src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/holder.js')}}"></script>
</body>
</html>

project/templates/baseOld.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HCP Digital Insights</title>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!--
    
    --<link rel="stylesheet" href="{{ url_for('static', filename='css/hcpdigital.css') }}">--
    
    <script src="{{ url_for('static', filename='js/jquery-3.1.1.slim.min.js')}}"></script>

    -- IE10 viewport hack for Surface/desktop Windows 8 bug --
    <script src="{{ url_for('static', filename='js/ie10-viewport-bug-workaround.js')}}"></script>
  -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}"> 
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"> 
  <!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
  <script src="{{ url_for('static', filename='js/tether.min.js')}}"></script>  
  <script src="{{ url_for('static', filename='js/jquery-3.1.1.slim.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/d3.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/crossfilter.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/dc.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/reductio.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/powerbi.min.js') }}"></script>
    <!--
      <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    -->
    <link href="https://harvesthq.github.io/chosen/chosen.css" rel="stylesheet" />
    <script src="https://harvesthq.github.io/chosen/chosen.jquery.js"></script>

    
    <script>
        $(document).ready(function() {

          //console.log($('#ddSegment'));
          //$('#ddSegment').select2();
          $(".chosen-select").chosen({no_results_text: "Oops, nothing found!"}); 
      });
      $(document).ready(function() {
      //$('.mdb-select').materialSelect();
    });
        </script>
      
  </head>
  <body>
    
    <!-- Navigation -->
    
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='images/HCP-Digital-Insights_Logo.png')}}" height="47px"></a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Settings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
        </ul>
        
      </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-xs-1 p-l-0 p-r-0" id="sidebar">
            <aside>
                <nav class="navbar navbar-inverse sidebar navbar-fixed-top" role="navigation">
                    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
              
              <div class="nav-side-menu">
                  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
                
                      <div class="menu-list">
                
                          <ul id="menu-content" class="menu-content collapse out">
                              <li data-toggle="collapse" data-target="#campaigns" class="collapsed">
                                  <a href="#"><i class="fa fa-globe fa-lg"></i> Campaigns <span class="arrow"></span></a>
                                </li>  
                                <ul class="sub-menu collapse" id="campaigns">
                                  <li><a href="{{url_for('dashboard.Campaign',id=1000)}}">Campaign 1</a></li>
                                  <li><a href="{{url_for('dashboard.Campaign',id=1001)}}">Campaign 2</a></li>
                              </ul>

                              <li>
                                <a href="#">
                                <i class="fa fa-dashboard fa-lg"></i> Campaign Information
                                </a>
                              </li>
                              <li data-toggle="collapse" data-target="#service" class="collapsed">
                                <a href="#"><i class="fa fa-globe fa-lg"></i> Insights Dashboards <span class="arrow"></span></a>
                              </li>  
                              <ul class="sub-menu collapse" id="service">
                                    <li><a href="{{url_for('dashboard.DeviceTypes')}}">Device Types</a></li>
                                    <li><a href="{{url_for('dashboard.ProfessionalInsights')}}">Professional Insights</a></li>
                                    <li><a href="{{url_for('dashboard.ContentInsights')}}">Content Insights</a></li>
                                </ul>
                  
              
                              <li data-toggle="collapse" data-target="#new" class="collapsed">
                                <a href="#"><i class="fa fa-car fa-lg"></i> Dashboard Filters <span class="arrow"></span></a>
                              </li>
                              <ul class="sub-menu collapse" id="new">
                                <li>                    
                                  Segment:
                                  <!--<select id="ddSegment">-->
                                  <!--<select class="js-example-basic-multiple" id="ddSegment" multiple="multiple">-->
                                    <!--<select class="mdb-select md-form colorful-select dropdown-primary" multiple searchable="Search here..">-->
                                      <!--
                                        <select data-placeholder="Choose a country..." multiple class="chosen-select11">
                                      {% for segment in segments %}
                                      <option value="{{ segment.id }}" >{{ segment.name}}</option>
                                      {% endfor %}
                                      </select>
                                    -->
                                </li>
                                <li>                                  
                                  <!--  
                                  Professions:
                                    <select id="ddprofession1">
                                        {% for profession in professions %}
                                        <option value="{{ profession.id }}" >{{ profession.name}}</option>
                                        {% endfor %}
                                      </select>
                                    -->
                                </li>
                                <li>
                                  <!--                                    
                                  Specialty Groups:
                                    <select id="ddspecialtyGroup1">
                                      {% for specialtyGroup in specialtyGroups %}
                                      <option value="{{ specialtyGroup.id }}" >{{ specialtyGroup.name}}</option>
                                      {% endfor %}
                                    </select>
                                  -->
                                </li>
                                <li> 
                                  <!--                                   
                                    Regions:
                                      <select id="ddGeoRegion1">
                                        {% for region in geoRegions %}
                                        <option value="{{ region.id }}" >{{ region.name}}</option>
                                        {% endfor %}
                                      </select>
                                    -->
                                  </li>
                              </ul>
                               <li>
                                <a href="#">
                                <i class="fa fa-user fa-lg"></i> Campaign Optimization
                                </a>
                                </li>
              
                               <li>
                                <a href="#">
                                <i class="fa fa-users fa-lg"></i> Export Dashboard
                                </a>
                              </li>
                              <li>
                                  <a href="#">
                                  <i class="fa fa-users fa-lg"></i> Print Dashboard
                                  </a>
                              </li>
                              <li>
                                  <a href="#">
                                  <i class="fa fa-users fa-lg"></i> Support
                                  </a>
                              </li>

                          </ul>
                   </div>
              </div>
                </nav>
                
              </aside>
            </div>
    ppp={{model}}

    <!-- Page Content -->
      {%block content%}
      {%endblock%}
      {% block footer %}
<!--
        <footer class="footer">
          <div class="container">
            <span class="text-muted">Place sticky footer content here.</span>
          </div>
        </footer>
      -->  
        {%endblock%}     

  </body>
</html>

project/templates/footer.html
{% block footer %}
<footer class="footer">
    <div class="container">
      <span class="text-muted">Place sticky footer content here.</span>
    </div>
  </footer>
  {%endblock%}